### ISSUE TITLE
setting working_dir causes oloop to hang

### ISSUE THREAD

**Issue by agarwal** [agarwal/oloop#31]
I pushed 2b1f4956e75b605a49f55786fe2a71e5ff64d413, but the feature doesn't work. Setting working_dir causes oloop to hang.

**Comment by Chris00** [comment]
Did you try with `oloop` being installed or with the local executable.  In any case, I cannot reproduce this bug — it either runs (with `oloop`) or fails (with `./app.native`).

Maybe you launched `oloop` in the devel. dir., in which cases it picks up `.ocamlinit`?  What happens if you pass the additional option `-noinit`?

**Comment by Chris00** [comment]
I think I got it.  The check whether toploop exists is done before changing directory (thus succeeds) but the relative executable is not found after the directory change.
